openapi: 3.0.0
info:
  title: AAA API
  version: 1.0.0
  description: AAA
paths: {}
components:
  schemas:
    Description:
      type: object
      required:
        - id
        - origin
        - number
        - condition
        - dimensions
        - attributes
      properties:
        id:
          type: integer
          format: int64
        origin:
          type: array
          items:
            type: string
        number:
          type: integer
          format: int64
        condition:
          type: string
        dimensions:
          type: array
          items:
            type: number
            format: int64
        attributes:
          type: array
          items:
            $ref: '#/components/schemas/Attribute'
    Attribute:
      type: object
      required:
        - id
        - type
      properties:
        id:
          type: string
        type:
          type: string
