import chevronRight from '@assets/icons/ic_chevron-right.svg?react';
import chevronDown from '@assets/icons/ic_chevron-down.svg?react';
import description from '@assets/icons/ic_description.svg?react';
import history from '@assets/icons/ic_history.svg?react';
import star from '@assets/icons/ic_star.svg?react';
import images from '@assets/icons/ic_images.svg?react';
import contact from '@assets/icons/ic_contact.svg?react';
import payment from '@assets/icons/ic_payment.svg?react';
import preview from '@assets/icons/ic_preview.svg?react';
import hide from '@assets/icons/ic_hide.svg?react';
import selectArrow from '@assets/icons/ic_select-arrow.svg?react';

export const iconChevronRight = chevronRight;
export const iconChevronDown = chevronDown;
export const iconDescription = description;
export const iconHistory = history;
export const iconStar = star;
export const iconImages = images;
export const iconContact = contact;
export const iconPayment = payment;
export const iconPreview = preview;
export const iconHide = hide;
export const iconSelectArrow = selectArrow;
