openapi: 3.0.0
info:
  title: AAA API
  version: 1.0.0
  description: AAA
paths: {}
components:
  schemas:
    Description:
      type: object
      required:
        - id
        - origin
        - number
        - condition
        - dimensions
        - attributes
      properties:
        id:
          type: integer
          format: int64
        origin:
          type: array
          items:
            type: string
        number:
          type: integer
          format: int64
        condition:
          type: string
        dimensions:
          type: array
          items:
            type: number
            format: int64
        attributes:
          type: array
          items:
            $ref: '#/components/schemas/ArtifactAttribute'
    ArtifactAttribute:
      type: object
      required:
        - id
        - type
      properties:
        id:
          type: string
        type:
          type: string
    History:
      type: object
      required:
        - id
        - entries
      properties:
        id:
          type: integer
          format: int64
        entries:
          type: array
          items:
            $ref: '#/components/schemas/HistoryEntry'
    HistoryEntry:
      type: object
      required:
        - date
        - amount
      properties:
        date:
          type: string
          format: date
        amount:
          type: string
          format: decimal
    Images:
      type: object
      required:
        - id
        - images
      properties:
        id:
          type: integer
          format: int64
        images:
          type: array
          items:
            $ref: '#/components/schemas/ImageUrl'
    ImageUrl:
      type: object
      properties:
        url:
          type: string
